//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

												

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using NHibernate.UserTypes;
using Pangea.BaseStructures;
using Pangea.BasicValidators;
using System.Linq;


//using Pangea.Hibernate.UserTypes;

namespace NGU.Core
{

    public class CImageBiometric : ConstField    
    {
		private ConstField _ID = null;
		private ConstField _IsWaived = null;
		private ConstField _Image = null;
		private ConstField _Template = null;
		private ConstField _CreateUserID = null;
		private ConstField _UpdateUserID = null;
		private ConstField _CreateDate = null;
		private ConstField _UpdateDate = null;
		private CRequest _Request = null;
		private CPerson _Person = null;
		private CImageType _ImageType = null;


        public CImageBiometric()
        {
			_ID = new ConstField("ID");
			_IsWaived = new ConstField("IsWaived");
			_Image = new ConstField("Image");
			_Template = new ConstField("Template");
			_CreateUserID = new ConstField("CreateUserID");
			_UpdateUserID = new ConstField("UpdateUserID");
			_CreateDate = new ConstField("CreateDate");
			_UpdateDate = new ConstField("UpdateDate");
			_Request = new CRequest("Request");
			_Person = new CPerson("Person");
			_ImageType = new CImageType("ImageType");
        }
        

        public CImageBiometric(string parent)
            : base(parent)
        {
			_ID = new ConstField("ID", parent);
			_IsWaived = new ConstField("IsWaived", parent);
			_Image = new ConstField("Image", parent);
			_Template = new ConstField("Template", parent);
			_CreateUserID = new ConstField("CreateUserID", parent);
			_UpdateUserID = new ConstField("UpdateUserID", parent);
			_CreateDate = new ConstField("CreateDate", parent);
			_UpdateDate = new ConstField("UpdateDate", parent);
			_Request = new CRequest("Request", parent);
			_Person = new CPerson("Person", parent);
			_ImageType = new CImageType("ImageType", parent);
        }

        public CImageBiometric(string value, string parent)
            : base(value, parent)
        {
			_ID = new ConstField("ID", FormatPath(value, parent));
			_IsWaived = new ConstField("IsWaived", FormatPath(value, parent));
			_Image = new ConstField("Image", FormatPath(value, parent));
			_Template = new ConstField("Template", FormatPath(value, parent));
			_CreateUserID = new ConstField("CreateUserID", FormatPath(value, parent));
			_UpdateUserID = new ConstField("UpdateUserID", FormatPath(value, parent));
			_CreateDate = new ConstField("CreateDate", FormatPath(value, parent));
			_UpdateDate = new ConstField("UpdateDate", FormatPath(value, parent));
			_Request = new CRequest("Request", FormatPath(value, parent));
			_Person = new CPerson("Person", FormatPath(value, parent));
			_ImageType = new CImageType("ImageType", FormatPath(value, parent));
        }
        
		public ConstField ID
        {
            get
            {
                return this._ID;
            }
        }
		public ConstField IsWaived
        {
            get
            {
                return this._IsWaived;
            }
        }
		public ConstField Image
        {
            get
            {
                return this._Image;
            }
        }
		public ConstField Template
        {
            get
            {
                return this._Template;
            }
        }
		public ConstField CreateUserID
        {
            get
            {
                return this._CreateUserID;
            }
        }
		public ConstField UpdateUserID
        {
            get
            {
                return this._UpdateUserID;
            }
        }
		public ConstField CreateDate
        {
            get
            {
                return this._CreateDate;
            }
        }
		public ConstField UpdateDate
        {
            get
            {
                return this._UpdateDate;
            }
        }
		public CRequest Request
        {
            get
            {
                return this._Request;
            }
        }
		public CPerson Person
        {
            get
            {
                return this._Person;
            }
        }
		public CImageType ImageType
        {
            get
            {
                return this._ImageType;
            }
        }

    }


	/// <summary>
	/// POCO for ImageBiometric. This class is autogenerated
	/// </summary>

	
	
	[Serializable]
	public partial  class ImageBiometric :  ObjectValidationBase  	{
		#region Consts
		
		private static CImageBiometric props = null;

		
		public static CImageBiometric Props
        {
            get
            {
				if (props == null)
				{
					props = new CImageBiometric();
				}
                return props;
            }
        }

		#endregion
		
		#region Fields
		

		private Int32 iD;

		private bool? isWaived;
	
	
		private Byte[] image;

		private Byte[] template;

		private Int32 createUserID;
	
		private Int32 updateUserID;
	
			private DateTime? createDate;

			private DateTime? updateDate;

		private Request request;
	
		private Person person;
	
		private ImageType imageType;
	
		#endregion

		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the ImageBiometric class
		/// </summary>
		public ImageBiometric()
		{
		}
	
		#endregion
	
		#region Properties
		
		/// <summary>
		/// Gets or sets the ID for the current ImageBiometric
		/// </summary>
		
	
	
[DataMember]
			public  virtual   Int32 ID
		{
			get 
			{ 
				return this.iD; 
			}
			set 
			{
				this.iD = value;
				NotifyPropertyChanged("ID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the IsWaived for the current ImageBiometric
		/// </summary>
		
	
	
[DataMember]
  		public virtual bool? IsWaived
  		{
			get 
			{ 
				return this.isWaived; 
			}
			set 
			{
				this.isWaived = value;
				NotifyPropertyChanged("IsWaived");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the Image for the current ImageBiometric
		/// </summary>
		
	
	
[DataMember]
			public  virtual   Byte[] Image
		{
			get 
			{ 
				return this.image; 
			}
			set 
			{
				this.image = value;
				NotifyPropertyChanged("Image");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the Template for the current ImageBiometric
		/// </summary>
		
	
	
[DataMember]
			public  virtual   Byte[] Template
		{
			get 
			{ 
				return this.template; 
			}
			set 
			{
				this.template = value;
				NotifyPropertyChanged("Template");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the CreateUserID for the current ImageBiometric
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  Int32 CreateUserID
  		{
			get 
			{ 
				return this.createUserID; 
			}
			set 
			{
				this.createUserID = value;
				NotifyPropertyChanged("CreateUserID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the UpdateUserID for the current ImageBiometric
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  Int32 UpdateUserID
  		{
			get 
			{ 
				return this.updateUserID; 
			}
			set 
			{
				this.updateUserID = value;
				NotifyPropertyChanged("UpdateUserID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the CreateDate for the current ImageBiometric
		/// </summary>
		
	
	
[DataMember]
		public virtual DateTime? CreateDate
		{
			get 
			{ 
				return this.createDate; 
			}
			set 
			{
				this.createDate = value;
				NotifyPropertyChanged("CreateDate");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the UpdateDate for the current ImageBiometric
		/// </summary>
		
	
	
[DataMember]
		public virtual DateTime? UpdateDate
		{
			get 
			{ 
				return this.updateDate; 
			}
			set 
			{
				this.updateDate = value;
				NotifyPropertyChanged("UpdateDate");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the Request for the current ImageBiometric
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  Request Request
  		{
			get 
			{ 
				return this.request; 
			}
			set 
			{
				this.request = value;
				NotifyPropertyChanged("Request");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the Person for the current ImageBiometric
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  Person Person
  		{
			get 
			{ 
				return this.person; 
			}
			set 
			{
				this.person = value;
				NotifyPropertyChanged("Person");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the ImageType for the current ImageBiometric
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  ImageType ImageType
  		{
			get 
			{ 
				return this.imageType; 
			}
			set 
			{
				this.imageType = value;
				NotifyPropertyChanged("ImageType");
			}
		}
/*
*/



		#endregion
		
		#region Equals override
			
		public override bool Equals(object obj)
		{
			if(obj == null)
				return false;
				
            var pi = obj.GetType().GetProperty("ID");
            
            if(pi == null)
            {
				return false;
            }
            
            var val = pi.GetValue(obj, null);
            if(val != null)
            {
				return val.Equals(ID);
			}
			else
			{
				#pragma warning disable CS0472 // Generated
				if(ID == null)
				#pragma warning restore CS0472 // Generated
					return true;
				else
					return false;
			}
		}	

		public override int GetHashCode()
        {
            return base.GetHashCode();
        }
		
	#endregion

	}	
}