//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

							

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using NHibernate.UserTypes;
using Pangea.BaseStructures;
using Pangea.BasicValidators;
using System.Linq;


//
namespace NGU.Core
{

    public class CLocalizedNames : ConstField    
    {
		private ConstField _ID = null;
		private ConstField _TableName = null;
		private ConstField _EN = null;
		private ConstField _FR = null;
		private ConstField _PT = null;
		private ConstField _SP = null;


        public CLocalizedNames()
        {
			_ID = new ConstField("ID");
			_TableName = new ConstField("TableName");
			_EN = new ConstField("EN");
			_FR = new ConstField("FR");
			_PT = new ConstField("PT");
			_SP = new ConstField("SP");
        }
        

        public CLocalizedNames(string parent)
            : base(parent)
        {
			_ID = new ConstField("ID", parent);
			_TableName = new ConstField("TableName", parent);
			_EN = new ConstField("EN", parent);
			_FR = new ConstField("FR", parent);
			_PT = new ConstField("PT", parent);
			_SP = new ConstField("SP", parent);
        }

        public CLocalizedNames(string value, string parent)
            : base(value, parent)
        {
			_ID = new ConstField("ID", FormatPath(value, parent));
			_TableName = new ConstField("TableName", FormatPath(value, parent));
			_EN = new ConstField("EN", FormatPath(value, parent));
			_FR = new ConstField("FR", FormatPath(value, parent));
			_PT = new ConstField("PT", FormatPath(value, parent));
			_SP = new ConstField("SP", FormatPath(value, parent));
        }
        
		public ConstField ID
        {
            get
            {
                return this._ID;
            }
        }
		public ConstField TableName
        {
            get
            {
                return this._TableName;
            }
        }
		public ConstField EN
        {
            get
            {
                return this._EN;
            }
        }
		public ConstField FR
        {
            get
            {
                return this._FR;
            }
        }
		public ConstField PT
        {
            get
            {
                return this._PT;
            }
        }
		public ConstField SP
        {
            get
            {
                return this._SP;
            }
        }

    }


	/// <summary>
	/// POCO for LocalizedNames. This class is autogenerated
	/// </summary>

	
	
	[Serializable]
	public partial  class LocalizedNames :  ObjectValidationBase  	{
		#region Consts
		
		private static CLocalizedNames props = null;

		
		public static CLocalizedNames Props
        {
            get
            {
				if (props == null)
				{
					props = new CLocalizedNames();
				}
                return props;
            }
        }

		#endregion
		
		#region Fields
		

		private String iD;

		private String tableName;
	
		private String eN;
	
		private String fR;
	
		private String pT;
	
		private String sP;
	
		#endregion

		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the LocalizedNames class
		/// </summary>
		public LocalizedNames()
		{
		}
	
		#endregion
	
		#region Properties
		
		/// <summary>
		/// Gets or sets the ID for the current LocalizedNames
		/// </summary>
		
	
	
[DataMember]
			public  virtual   String ID
		{
			get 
			{ 
				return this.iD; 
			}
			set 
			{
				this.iD = value;
				NotifyPropertyChanged("ID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the TableName for the current LocalizedNames
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  String TableName
  		{
			get 
			{ 
				return this.tableName; 
			}
			set 
			{
				this.tableName = value;
				NotifyPropertyChanged("TableName");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the EN for the current LocalizedNames
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  String EN
  		{
			get 
			{ 
				return this.eN; 
			}
			set 
			{
				this.eN = value;
				NotifyPropertyChanged("EN");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the FR for the current LocalizedNames
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  String FR
  		{
			get 
			{ 
				return this.fR; 
			}
			set 
			{
				this.fR = value;
				NotifyPropertyChanged("FR");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the PT for the current LocalizedNames
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  String PT
  		{
			get 
			{ 
				return this.pT; 
			}
			set 
			{
				this.pT = value;
				NotifyPropertyChanged("PT");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the SP for the current LocalizedNames
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  String SP
  		{
			get 
			{ 
				return this.sP; 
			}
			set 
			{
				this.sP = value;
				NotifyPropertyChanged("SP");
			}
		}
/*
*/



		#endregion
		
		#region Equals override
			
		public override bool Equals(object obj)
		{
			if(obj == null)
				return false;
				
            var pi = obj.GetType().GetProperty("ID");
            
            if(pi == null)
            {
				return false;
            }
            
            var val = pi.GetValue(obj, null);
            if(val != null)
            {
				return val.Equals(ID);
			}
			else
			{
				#pragma warning disable CS0472 // Generated
				if(ID == null)
				#pragma warning restore CS0472 // Generated
					return true;
				else
					return false;
			}
		}	

		public override int GetHashCode()
        {
            return base.GetHashCode();
        }
		
	#endregion

	}	
}