//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

													

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using NHibernate.UserTypes;
using Pangea.BaseStructures;
using Pangea.BasicValidators;
using System.Linq;


//
namespace NGU.Core
{

    public class CPerson : ConstField    
    {
		private ConstField _ID = null;
		private ConstField _NationalityID = null;
		private ConstField _GenderID = null;
		private ConstField _FirstName = null;
		private ConstField _MiddleName = null;
		private ConstField _LastName = null;
		private ConstField _BirthDate = null;
		private ConstField _StatusID = null;
		private ConstField _CreateUserID = null;
		private ConstField _UpdateUserID = null;
		private ConstField _CreateDate = null;
		private ConstField _UpdateDate = null;


        public CPerson()
        {
			_ID = new ConstField("ID");
			_NationalityID = new ConstField("NationalityID");
			_GenderID = new ConstField("GenderID");
			_FirstName = new ConstField("FirstName");
			_MiddleName = new ConstField("MiddleName");
			_LastName = new ConstField("LastName");
			_BirthDate = new ConstField("BirthDate");
			_StatusID = new ConstField("StatusID");
			_CreateUserID = new ConstField("CreateUserID");
			_UpdateUserID = new ConstField("UpdateUserID");
			_CreateDate = new ConstField("CreateDate");
			_UpdateDate = new ConstField("UpdateDate");
        }
        

        public CPerson(string parent)
            : base(parent)
        {
			_ID = new ConstField("ID", parent);
			_NationalityID = new ConstField("NationalityID", parent);
			_GenderID = new ConstField("GenderID", parent);
			_FirstName = new ConstField("FirstName", parent);
			_MiddleName = new ConstField("MiddleName", parent);
			_LastName = new ConstField("LastName", parent);
			_BirthDate = new ConstField("BirthDate", parent);
			_StatusID = new ConstField("StatusID", parent);
			_CreateUserID = new ConstField("CreateUserID", parent);
			_UpdateUserID = new ConstField("UpdateUserID", parent);
			_CreateDate = new ConstField("CreateDate", parent);
			_UpdateDate = new ConstField("UpdateDate", parent);
        }

        public CPerson(string value, string parent)
            : base(value, parent)
        {
			_ID = new ConstField("ID", FormatPath(value, parent));
			_NationalityID = new ConstField("NationalityID", FormatPath(value, parent));
			_GenderID = new ConstField("GenderID", FormatPath(value, parent));
			_FirstName = new ConstField("FirstName", FormatPath(value, parent));
			_MiddleName = new ConstField("MiddleName", FormatPath(value, parent));
			_LastName = new ConstField("LastName", FormatPath(value, parent));
			_BirthDate = new ConstField("BirthDate", FormatPath(value, parent));
			_StatusID = new ConstField("StatusID", FormatPath(value, parent));
			_CreateUserID = new ConstField("CreateUserID", FormatPath(value, parent));
			_UpdateUserID = new ConstField("UpdateUserID", FormatPath(value, parent));
			_CreateDate = new ConstField("CreateDate", FormatPath(value, parent));
			_UpdateDate = new ConstField("UpdateDate", FormatPath(value, parent));
        }
        
		public ConstField ID
        {
            get
            {
                return this._ID;
            }
        }
		public ConstField NationalityID
        {
            get
            {
                return this._NationalityID;
            }
        }
		public ConstField GenderID
        {
            get
            {
                return this._GenderID;
            }
        }
		public ConstField FirstName
        {
            get
            {
                return this._FirstName;
            }
        }
		public ConstField MiddleName
        {
            get
            {
                return this._MiddleName;
            }
        }
		public ConstField LastName
        {
            get
            {
                return this._LastName;
            }
        }
		public ConstField BirthDate
        {
            get
            {
                return this._BirthDate;
            }
        }
		public ConstField StatusID
        {
            get
            {
                return this._StatusID;
            }
        }
		public ConstField CreateUserID
        {
            get
            {
                return this._CreateUserID;
            }
        }
		public ConstField UpdateUserID
        {
            get
            {
                return this._UpdateUserID;
            }
        }
		public ConstField CreateDate
        {
            get
            {
                return this._CreateDate;
            }
        }
		public ConstField UpdateDate
        {
            get
            {
                return this._UpdateDate;
            }
        }

    }


	/// <summary>
	/// POCO for Person. This class is autogenerated
	/// </summary>

	
	
	[Serializable]
	public partial  class Person :  ObjectValidationBase  	{
		#region Consts
		
		private static CPerson props = null;

		
		public static CPerson Props
        {
            get
            {
				if (props == null)
				{
					props = new CPerson();
				}
                return props;
            }
        }

		#endregion
		
		#region Fields
		

		private Int64 iD;

		private Int64? nationalityID;

		private Int64? genderID;

		private String firstName;
	
		private String middleName;
	
		private String lastName;
	
			private DateTime? birthDate;

		private Int64 statusID;
	
		private Int64 createUserID;
	
		private Int64 updateUserID;
	
			private DateTime? createDate;

			private DateTime? updateDate;

		#endregion

		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the Person class
		/// </summary>
		public Person()
		{
		}
	
		#endregion
	
		#region Properties
		
		/// <summary>
		/// Gets or sets the ID for the current Person
		/// </summary>
		
	
	
[DataMember]
			public  virtual   Int64 ID
		{
			get 
			{ 
				return this.iD; 
			}
			set 
			{
				this.iD = value;
				NotifyPropertyChanged("ID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the NationalityID for the current Person
		/// </summary>
		
	
	
[DataMember]
			public  virtual   Int64? NationalityID
		{
			get 
			{ 
				return this.nationalityID; 
			}
			set 
			{
				this.nationalityID = value;
				NotifyPropertyChanged("NationalityID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the GenderID for the current Person
		/// </summary>
		
	
	
[DataMember]
			public  virtual   Int64? GenderID
		{
			get 
			{ 
				return this.genderID; 
			}
			set 
			{
				this.genderID = value;
				NotifyPropertyChanged("GenderID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the FirstName for the current Person
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  String FirstName
  		{
			get 
			{ 
				return this.firstName; 
			}
			set 
			{
				this.firstName = value;
				NotifyPropertyChanged("FirstName");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the MiddleName for the current Person
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  String MiddleName
  		{
			get 
			{ 
				return this.middleName; 
			}
			set 
			{
				this.middleName = value;
				NotifyPropertyChanged("MiddleName");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the LastName for the current Person
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  String LastName
  		{
			get 
			{ 
				return this.lastName; 
			}
			set 
			{
				this.lastName = value;
				NotifyPropertyChanged("LastName");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the BirthDate for the current Person
		/// </summary>
		
	
	
[DataMember]
		public virtual DateTime? BirthDate
		{
			get 
			{ 
				return this.birthDate; 
			}
			set 
			{
				this.birthDate = value;
				NotifyPropertyChanged("BirthDate");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the StatusID for the current Person
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  Int64 StatusID
  		{
			get 
			{ 
				return this.statusID; 
			}
			set 
			{
				this.statusID = value;
				NotifyPropertyChanged("StatusID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the CreateUserID for the current Person
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  Int64 CreateUserID
  		{
			get 
			{ 
				return this.createUserID; 
			}
			set 
			{
				this.createUserID = value;
				NotifyPropertyChanged("CreateUserID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the UpdateUserID for the current Person
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  Int64 UpdateUserID
  		{
			get 
			{ 
				return this.updateUserID; 
			}
			set 
			{
				this.updateUserID = value;
				NotifyPropertyChanged("UpdateUserID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the CreateDate for the current Person
		/// </summary>
		
	
	
[DataMember]
		public virtual DateTime? CreateDate
		{
			get 
			{ 
				return this.createDate; 
			}
			set 
			{
				this.createDate = value;
				NotifyPropertyChanged("CreateDate");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the UpdateDate for the current Person
		/// </summary>
		
	
	
[DataMember]
		public virtual DateTime? UpdateDate
		{
			get 
			{ 
				return this.updateDate; 
			}
			set 
			{
				this.updateDate = value;
				NotifyPropertyChanged("UpdateDate");
			}
		}
/*
*/



		#endregion
		
		#region Equals override
			
		public override bool Equals(object obj)
		{
			if(obj == null)
				return false;
				
            var pi = obj.GetType().GetProperty("ID");
            
            if(pi == null)
            {
				return false;
            }
            
            var val = pi.GetValue(obj, null);
            if(val != null)
            {
				return val.Equals(ID);
			}
			else
			{
				#pragma warning disable CS0472 // Generated
				if(ID == null)
				#pragma warning restore CS0472 // Generated
					return true;
				else
					return false;
			}
		}	

		public override int GetHashCode()
        {
            return base.GetHashCode();
        }
		
	#endregion

	}	
}