//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

																														

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using NHibernate.UserTypes;
using Pangea.BaseStructures;
using Pangea.BasicValidators;
using System.Linq;


//using Pangea.Hibernate.UserTypes;

namespace NGU.Core
{

    public class CRequest : ConstField    
    {
		private ConstField _ID = null;
		private ConstField _Num = null;
		private ConstField _IdenTypeID = null;
		private ConstField _IdenNum = null;
		private ConstField _IdenCountryID = null;
		private ConstField _DocCode = null;
		private ConstField _DocNationalityID = null;
		private ConstField _DocExpirationDate = null;
		private ConstField _FirstName = null;
		private ConstField _MiddleName = null;
		private ConstField _LastName = null;
		private ConstField _GenderID = null;
		private ConstField _BirthDate = null;
		private ConstField _IsMatch1ToManyRes = null;
		private ConstField _IsMatch1ToOneRes = null;
		private ConstField _IsMatchTextDataRes = null;
		private ConstField _StatusDate = null;
		private ConstField _Remarks = null;
		private ConstField _PriorityID = null;
		private ConstField _SiteID = null;
		private ConstField _CreateUserID = null;
		private ConstField _UpdateUserID = null;
		private ConstField _CreateDate = null;
		private ConstField _UpdateDate = null;
		private CRequestType _RequestType = null;
		private CRequestSubType _RequestSubType = null;
		private CPerson _Person = null;
		private CRequestStatus _RequestStatus = null;
		private CRequestReason _RequestReason = null;


        public CRequest()
        {
			_ID = new ConstField("ID");
			_Num = new ConstField("Num");
			_IdenTypeID = new ConstField("IdenTypeID");
			_IdenNum = new ConstField("IdenNum");
			_IdenCountryID = new ConstField("IdenCountryID");
			_DocCode = new ConstField("DocCode");
			_DocNationalityID = new ConstField("DocNationalityID");
			_DocExpirationDate = new ConstField("DocExpirationDate");
			_FirstName = new ConstField("FirstName");
			_MiddleName = new ConstField("MiddleName");
			_LastName = new ConstField("LastName");
			_GenderID = new ConstField("GenderID");
			_BirthDate = new ConstField("BirthDate");
			_IsMatch1ToManyRes = new ConstField("IsMatch1ToManyRes");
			_IsMatch1ToOneRes = new ConstField("IsMatch1ToOneRes");
			_IsMatchTextDataRes = new ConstField("IsMatchTextDataRes");
			_StatusDate = new ConstField("StatusDate");
			_Remarks = new ConstField("Remarks");
			_PriorityID = new ConstField("PriorityID");
			_SiteID = new ConstField("SiteID");
			_CreateUserID = new ConstField("CreateUserID");
			_UpdateUserID = new ConstField("UpdateUserID");
			_CreateDate = new ConstField("CreateDate");
			_UpdateDate = new ConstField("UpdateDate");
			_RequestType = new CRequestType("RequestType");
			_RequestSubType = new CRequestSubType("RequestSubType");
			_Person = new CPerson("Person");
			_RequestStatus = new CRequestStatus("RequestStatus");
			_RequestReason = new CRequestReason("RequestReason");
        }
        

        public CRequest(string parent)
            : base(parent)
        {
			_ID = new ConstField("ID", parent);
			_Num = new ConstField("Num", parent);
			_IdenTypeID = new ConstField("IdenTypeID", parent);
			_IdenNum = new ConstField("IdenNum", parent);
			_IdenCountryID = new ConstField("IdenCountryID", parent);
			_DocCode = new ConstField("DocCode", parent);
			_DocNationalityID = new ConstField("DocNationalityID", parent);
			_DocExpirationDate = new ConstField("DocExpirationDate", parent);
			_FirstName = new ConstField("FirstName", parent);
			_MiddleName = new ConstField("MiddleName", parent);
			_LastName = new ConstField("LastName", parent);
			_GenderID = new ConstField("GenderID", parent);
			_BirthDate = new ConstField("BirthDate", parent);
			_IsMatch1ToManyRes = new ConstField("IsMatch1ToManyRes", parent);
			_IsMatch1ToOneRes = new ConstField("IsMatch1ToOneRes", parent);
			_IsMatchTextDataRes = new ConstField("IsMatchTextDataRes", parent);
			_StatusDate = new ConstField("StatusDate", parent);
			_Remarks = new ConstField("Remarks", parent);
			_PriorityID = new ConstField("PriorityID", parent);
			_SiteID = new ConstField("SiteID", parent);
			_CreateUserID = new ConstField("CreateUserID", parent);
			_UpdateUserID = new ConstField("UpdateUserID", parent);
			_CreateDate = new ConstField("CreateDate", parent);
			_UpdateDate = new ConstField("UpdateDate", parent);
			_RequestType = new CRequestType("RequestType", parent);
			_RequestSubType = new CRequestSubType("RequestSubType", parent);
			_Person = new CPerson("Person", parent);
			_RequestStatus = new CRequestStatus("RequestStatus", parent);
			_RequestReason = new CRequestReason("RequestReason", parent);
        }

        public CRequest(string value, string parent)
            : base(value, parent)
        {
			_ID = new ConstField("ID", FormatPath(value, parent));
			_Num = new ConstField("Num", FormatPath(value, parent));
			_IdenTypeID = new ConstField("IdenTypeID", FormatPath(value, parent));
			_IdenNum = new ConstField("IdenNum", FormatPath(value, parent));
			_IdenCountryID = new ConstField("IdenCountryID", FormatPath(value, parent));
			_DocCode = new ConstField("DocCode", FormatPath(value, parent));
			_DocNationalityID = new ConstField("DocNationalityID", FormatPath(value, parent));
			_DocExpirationDate = new ConstField("DocExpirationDate", FormatPath(value, parent));
			_FirstName = new ConstField("FirstName", FormatPath(value, parent));
			_MiddleName = new ConstField("MiddleName", FormatPath(value, parent));
			_LastName = new ConstField("LastName", FormatPath(value, parent));
			_GenderID = new ConstField("GenderID", FormatPath(value, parent));
			_BirthDate = new ConstField("BirthDate", FormatPath(value, parent));
			_IsMatch1ToManyRes = new ConstField("IsMatch1ToManyRes", FormatPath(value, parent));
			_IsMatch1ToOneRes = new ConstField("IsMatch1ToOneRes", FormatPath(value, parent));
			_IsMatchTextDataRes = new ConstField("IsMatchTextDataRes", FormatPath(value, parent));
			_StatusDate = new ConstField("StatusDate", FormatPath(value, parent));
			_Remarks = new ConstField("Remarks", FormatPath(value, parent));
			_PriorityID = new ConstField("PriorityID", FormatPath(value, parent));
			_SiteID = new ConstField("SiteID", FormatPath(value, parent));
			_CreateUserID = new ConstField("CreateUserID", FormatPath(value, parent));
			_UpdateUserID = new ConstField("UpdateUserID", FormatPath(value, parent));
			_CreateDate = new ConstField("CreateDate", FormatPath(value, parent));
			_UpdateDate = new ConstField("UpdateDate", FormatPath(value, parent));
			_RequestType = new CRequestType("RequestType", FormatPath(value, parent));
			_RequestSubType = new CRequestSubType("RequestSubType", FormatPath(value, parent));
			_Person = new CPerson("Person", FormatPath(value, parent));
			_RequestStatus = new CRequestStatus("RequestStatus", FormatPath(value, parent));
			_RequestReason = new CRequestReason("RequestReason", FormatPath(value, parent));
        }
        
		public ConstField ID
        {
            get
            {
                return this._ID;
            }
        }
		public ConstField Num
        {
            get
            {
                return this._Num;
            }
        }
		public ConstField IdenTypeID
        {
            get
            {
                return this._IdenTypeID;
            }
        }
		public ConstField IdenNum
        {
            get
            {
                return this._IdenNum;
            }
        }
		public ConstField IdenCountryID
        {
            get
            {
                return this._IdenCountryID;
            }
        }
		public ConstField DocCode
        {
            get
            {
                return this._DocCode;
            }
        }
		public ConstField DocNationalityID
        {
            get
            {
                return this._DocNationalityID;
            }
        }
		public ConstField DocExpirationDate
        {
            get
            {
                return this._DocExpirationDate;
            }
        }
		public ConstField FirstName
        {
            get
            {
                return this._FirstName;
            }
        }
		public ConstField MiddleName
        {
            get
            {
                return this._MiddleName;
            }
        }
		public ConstField LastName
        {
            get
            {
                return this._LastName;
            }
        }
		public ConstField GenderID
        {
            get
            {
                return this._GenderID;
            }
        }
		public ConstField BirthDate
        {
            get
            {
                return this._BirthDate;
            }
        }
		public ConstField IsMatch1ToManyRes
        {
            get
            {
                return this._IsMatch1ToManyRes;
            }
        }
		public ConstField IsMatch1ToOneRes
        {
            get
            {
                return this._IsMatch1ToOneRes;
            }
        }
		public ConstField IsMatchTextDataRes
        {
            get
            {
                return this._IsMatchTextDataRes;
            }
        }
		public ConstField StatusDate
        {
            get
            {
                return this._StatusDate;
            }
        }
		public ConstField Remarks
        {
            get
            {
                return this._Remarks;
            }
        }
		public ConstField PriorityID
        {
            get
            {
                return this._PriorityID;
            }
        }
		public ConstField SiteID
        {
            get
            {
                return this._SiteID;
            }
        }
		public ConstField CreateUserID
        {
            get
            {
                return this._CreateUserID;
            }
        }
		public ConstField UpdateUserID
        {
            get
            {
                return this._UpdateUserID;
            }
        }
		public ConstField CreateDate
        {
            get
            {
                return this._CreateDate;
            }
        }
		public ConstField UpdateDate
        {
            get
            {
                return this._UpdateDate;
            }
        }
		public CRequestType RequestType
        {
            get
            {
                return this._RequestType;
            }
        }
		public CRequestSubType RequestSubType
        {
            get
            {
                return this._RequestSubType;
            }
        }
		public CPerson Person
        {
            get
            {
                return this._Person;
            }
        }
		public CRequestStatus RequestStatus
        {
            get
            {
                return this._RequestStatus;
            }
        }
		public CRequestReason RequestReason
        {
            get
            {
                return this._RequestReason;
            }
        }

    }


	/// <summary>
	/// POCO for Request. This class is autogenerated
	/// </summary>

	
	
	[Serializable]
	public partial  class Request :  ObjectValidationBase  	{
		#region Consts
		
		private static CRequest props = null;

		
		public static CRequest Props
        {
            get
            {
				if (props == null)
				{
					props = new CRequest();
				}
                return props;
            }
        }

		#endregion
		
		#region Fields
		

		private Int64 iD;

		private String num;
	
		private Int32 idenTypeID;
	
		private String idenNum;
	
		private Int32? idenCountryID;

		private String docCode;
	
		private Int64? docNationalityID;

			private DateTime? docExpirationDate;

		private String firstName;
	
		private String middleName;
	
		private String lastName;
	
		private Int32? genderID;

			private DateTime? birthDate;

		private bool? isMatch1ToManyRes;
	
	
		private bool? isMatch1ToOneRes;
	
	
		private bool? isMatchTextDataRes;
	
	
			private DateTime? statusDate;

		private String remarks;
	
		private Int32? priorityID;

		private Int32? siteID;

		private Int64 createUserID;
	
		private Int64 updateUserID;
	
			private DateTime? createDate;

			private DateTime? updateDate;

		private RequestType requestType;
	
		private RequestSubType requestSubType;
	
		private Person person;
	
		private RequestStatus requestStatus;
	
		private RequestReason requestReason;
	
		#endregion

		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the Request class
		/// </summary>
		public Request()
		{
		}
	
		#endregion
	
		#region Properties
		
		/// <summary>
		/// Gets or sets the ID for the current Request
		/// </summary>
		
	
	
[DataMember]
			public  virtual   Int64 ID
		{
			get 
			{ 
				return this.iD; 
			}
			set 
			{
				this.iD = value;
				NotifyPropertyChanged("ID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the Num for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  String Num
  		{
			get 
			{ 
				return this.num; 
			}
			set 
			{
				this.num = value;
				NotifyPropertyChanged("Num");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the IdenTypeID for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  Int32 IdenTypeID
  		{
			get 
			{ 
				return this.idenTypeID; 
			}
			set 
			{
				this.idenTypeID = value;
				NotifyPropertyChanged("IdenTypeID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the IdenNum for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  String IdenNum
  		{
			get 
			{ 
				return this.idenNum; 
			}
			set 
			{
				this.idenNum = value;
				NotifyPropertyChanged("IdenNum");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the IdenCountryID for the current Request
		/// </summary>
		
	
	
[DataMember]
			public  virtual   Int32? IdenCountryID
		{
			get 
			{ 
				return this.idenCountryID; 
			}
			set 
			{
				this.idenCountryID = value;
				NotifyPropertyChanged("IdenCountryID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the DocCode for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  String DocCode
  		{
			get 
			{ 
				return this.docCode; 
			}
			set 
			{
				this.docCode = value;
				NotifyPropertyChanged("DocCode");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the DocNationalityID for the current Request
		/// </summary>
		
	
	
[DataMember]
			public  virtual   Int64? DocNationalityID
		{
			get 
			{ 
				return this.docNationalityID; 
			}
			set 
			{
				this.docNationalityID = value;
				NotifyPropertyChanged("DocNationalityID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the DocExpirationDate for the current Request
		/// </summary>
		
	
	
[DataMember]
		public virtual DateTime? DocExpirationDate
		{
			get 
			{ 
				return this.docExpirationDate; 
			}
			set 
			{
				this.docExpirationDate = value;
				NotifyPropertyChanged("DocExpirationDate");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the FirstName for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  String FirstName
  		{
			get 
			{ 
				return this.firstName; 
			}
			set 
			{
				this.firstName = value;
				NotifyPropertyChanged("FirstName");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the MiddleName for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  String MiddleName
  		{
			get 
			{ 
				return this.middleName; 
			}
			set 
			{
				this.middleName = value;
				NotifyPropertyChanged("MiddleName");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the LastName for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  String LastName
  		{
			get 
			{ 
				return this.lastName; 
			}
			set 
			{
				this.lastName = value;
				NotifyPropertyChanged("LastName");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the GenderID for the current Request
		/// </summary>
		
	
	
[DataMember]
			public  virtual   Int32? GenderID
		{
			get 
			{ 
				return this.genderID; 
			}
			set 
			{
				this.genderID = value;
				NotifyPropertyChanged("GenderID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the BirthDate for the current Request
		/// </summary>
		
	
	
[DataMember]
		public virtual DateTime? BirthDate
		{
			get 
			{ 
				return this.birthDate; 
			}
			set 
			{
				this.birthDate = value;
				NotifyPropertyChanged("BirthDate");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the IsMatch1ToManyRes for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public virtual bool? IsMatch1ToManyRes
  		{
			get 
			{ 
				return this.isMatch1ToManyRes; 
			}
			set 
			{
				this.isMatch1ToManyRes = value;
				NotifyPropertyChanged("IsMatch1ToManyRes");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the IsMatch1ToOneRes for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public virtual bool? IsMatch1ToOneRes
  		{
			get 
			{ 
				return this.isMatch1ToOneRes; 
			}
			set 
			{
				this.isMatch1ToOneRes = value;
				NotifyPropertyChanged("IsMatch1ToOneRes");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the IsMatchTextDataRes for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public virtual bool? IsMatchTextDataRes
  		{
			get 
			{ 
				return this.isMatchTextDataRes; 
			}
			set 
			{
				this.isMatchTextDataRes = value;
				NotifyPropertyChanged("IsMatchTextDataRes");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the StatusDate for the current Request
		/// </summary>
		
	
	
[DataMember]
		public virtual DateTime? StatusDate
		{
			get 
			{ 
				return this.statusDate; 
			}
			set 
			{
				this.statusDate = value;
				NotifyPropertyChanged("StatusDate");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the Remarks for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  String Remarks
  		{
			get 
			{ 
				return this.remarks; 
			}
			set 
			{
				this.remarks = value;
				NotifyPropertyChanged("Remarks");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the PriorityID for the current Request
		/// </summary>
		
	
	
[DataMember]
			public  virtual   Int32? PriorityID
		{
			get 
			{ 
				return this.priorityID; 
			}
			set 
			{
				this.priorityID = value;
				NotifyPropertyChanged("PriorityID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the SiteID for the current Request
		/// </summary>
		
	
	
[DataMember]
			public  virtual   Int32? SiteID
		{
			get 
			{ 
				return this.siteID; 
			}
			set 
			{
				this.siteID = value;
				NotifyPropertyChanged("SiteID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the CreateUserID for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  Int64 CreateUserID
  		{
			get 
			{ 
				return this.createUserID; 
			}
			set 
			{
				this.createUserID = value;
				NotifyPropertyChanged("CreateUserID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the UpdateUserID for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  Int64 UpdateUserID
  		{
			get 
			{ 
				return this.updateUserID; 
			}
			set 
			{
				this.updateUserID = value;
				NotifyPropertyChanged("UpdateUserID");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the CreateDate for the current Request
		/// </summary>
		
	
	
[DataMember]
		public virtual DateTime? CreateDate
		{
			get 
			{ 
				return this.createDate; 
			}
			set 
			{
				this.createDate = value;
				NotifyPropertyChanged("CreateDate");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the UpdateDate for the current Request
		/// </summary>
		
	
	
[DataMember]
		public virtual DateTime? UpdateDate
		{
			get 
			{ 
				return this.updateDate; 
			}
			set 
			{
				this.updateDate = value;
				NotifyPropertyChanged("UpdateDate");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the RequestType for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  RequestType RequestType
  		{
			get 
			{ 
				return this.requestType; 
			}
			set 
			{
				this.requestType = value;
				NotifyPropertyChanged("RequestType");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the RequestSubType for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  RequestSubType RequestSubType
  		{
			get 
			{ 
				return this.requestSubType; 
			}
			set 
			{
				this.requestSubType = value;
				NotifyPropertyChanged("RequestSubType");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the Person for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  Person Person
  		{
			get 
			{ 
				return this.person; 
			}
			set 
			{
				this.person = value;
				NotifyPropertyChanged("Person");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the RequestStatus for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  RequestStatus RequestStatus
  		{
			get 
			{ 
				return this.requestStatus; 
			}
			set 
			{
				this.requestStatus = value;
				NotifyPropertyChanged("RequestStatus");
			}
		}
/*
*/

		/// <summary>
		/// Gets or sets the RequestReason for the current Request
		/// </summary>
		
	
	
[DataMember]
  		public  virtual  RequestReason RequestReason
  		{
			get 
			{ 
				return this.requestReason; 
			}
			set 
			{
				this.requestReason = value;
				NotifyPropertyChanged("RequestReason");
			}
		}
/*
*/



		#endregion
		
		#region Equals override
			
		public override bool Equals(object obj)
		{
			if(obj == null)
				return false;
				
            var pi = obj.GetType().GetProperty("ID");
            
            if(pi == null)
            {
				return false;
            }
            
            var val = pi.GetValue(obj, null);
            if(val != null)
            {
				return val.Equals(ID);
			}
			else
			{
				#pragma warning disable CS0472 // Generated
				if(ID == null)
				#pragma warning restore CS0472 // Generated
					return true;
				else
					return false;
			}
		}	

		public override int GetHashCode()
        {
            return base.GetHashCode();
        }
		
	#endregion

	}	
}