//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGU.Interfaces.ApiAdmin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModuleTypes", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Enums")]
    public enum ModuleTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Global = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BlackList = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Identification = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserValidation", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Core")]
    [System.SerializableAttribute()]
    public partial class UserValidation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.User LoggedUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.UserLoginResultTypes LoginResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pangea.MultiLanguage.Languages SelectedLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.UserValidationTypes UserValidationTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.User LoggedUser {
            get {
                return this.LoggedUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LoggedUserField, value) != true)) {
                    this.LoggedUserField = value;
                    this.RaisePropertyChanged("LoggedUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.UserLoginResultTypes LoginResult {
            get {
                return this.LoginResultField;
            }
            set {
                if ((this.LoginResultField.Equals(value) != true)) {
                    this.LoginResultField = value;
                    this.RaisePropertyChanged("LoginResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pangea.MultiLanguage.Languages SelectedLanguage {
            get {
                return this.SelectedLanguageField;
            }
            set {
                if ((this.SelectedLanguageField.Equals(value) != true)) {
                    this.SelectedLanguageField = value;
                    this.RaisePropertyChanged("SelectedLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.UserValidationTypes UserValidationType {
            get {
                return this.UserValidationTypeField;
            }
            set {
                if ((this.UserValidationTypeField.Equals(value) != true)) {
                    this.UserValidationTypeField = value;
                    this.RaisePropertyChanged("UserValidationType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Core")]
    [System.SerializableAttribute()]
    public partial class User : Pangea.BaseStructures.ObjectValidationBase, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreateUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Finger1NumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Finger1WsqBlobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Finger2NumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Finger2WsqBlobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdenCountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdenNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.IdenType IdenTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastPasswordUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.Menu[] MenusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NeedFPFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.Role[] RolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.Site SiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpdateUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreateUserID {
            get {
                return this.CreateUserIDField;
            }
            set {
                this.CreateUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Finger1Num {
            get {
                return this.Finger1NumField;
            }
            set {
                this.Finger1NumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Finger1WsqBlob {
            get {
                return this.Finger1WsqBlobField;
            }
            set {
                this.Finger1WsqBlobField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Finger2Num {
            get {
                return this.Finger2NumField;
            }
            set {
                this.Finger2NumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Finger2WsqBlob {
            get {
                return this.Finger2WsqBlobField;
            }
            set {
                this.Finger2WsqBlobField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdenCountryID {
            get {
                return this.IdenCountryIDField;
            }
            set {
                this.IdenCountryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdenNum {
            get {
                return this.IdenNumField;
            }
            set {
                this.IdenNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.IdenType IdenType {
            get {
                return this.IdenTypeField;
            }
            set {
                this.IdenTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastLogin {
            get {
                return this.LastLoginField;
            }
            set {
                this.LastLoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastPasswordUpdate {
            get {
                return this.LastPasswordUpdateField;
            }
            set {
                this.LastPasswordUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.Menu[] Menus {
            get {
                return this.MenusField;
            }
            set {
                this.MenusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NeedFPFlag {
            get {
                return this.NeedFPFlagField;
            }
            set {
                this.NeedFPFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Photo {
            get {
                return this.PhotoField;
            }
            set {
                this.PhotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.Role[] Roles {
            get {
                return this.RolesField;
            }
            set {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Signature {
            get {
                return this.SignatureField;
            }
            set {
                this.SignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.Site Site {
            get {
                return this.SiteField;
            }
            set {
                this.SiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                this.SurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateDateTime {
            get {
                return this.UpdateDateTimeField;
            }
            set {
                this.UpdateDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdateUserID {
            get {
                return this.UpdateUserIDField;
            }
            set {
                this.UpdateUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserStatus {
            get {
                return this.UserStatusField;
            }
            set {
                this.UserStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                this.UsernameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLoginResultTypes", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Enums")]
    public enum UserLoginResultTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faild = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChangePasswordRequired = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserValidationTypes", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Enums")]
    public enum UserValidationTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faild = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordIncorrect = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotActive = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserLoggedToManyTimes = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NewAndOldPasswordMatch = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdenType", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Core")]
    [System.SerializableAttribute()]
    public partial class IdenType : Pangea.BaseStructures.MultiLanguage, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveRecordFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultCountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DefaultFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaskFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIdentityFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHubField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActiveRecordFlag {
            get {
                return this.ActiveRecordFlagField;
            }
            set {
                this.ActiveRecordFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultCountryID {
            get {
                return this.DefaultCountryIDField;
            }
            set {
                this.DefaultCountryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DefaultFlag {
            get {
                return this.DefaultFlagField;
            }
            set {
                this.DefaultFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaskFormat {
            get {
                return this.MaskFormatField;
            }
            set {
                this.MaskFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonIdentityFlag {
            get {
                return this.PersonIdentityFlagField;
            }
            set {
                this.PersonIdentityFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHub {
            get {
                return this.ServerLangHubField;
            }
            set {
                this.ServerLangHubField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Site", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Core")]
    [System.SerializableAttribute()]
    public partial class Site : Pangea.BaseStructures.MultiLanguage, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveRecordFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreateUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDirtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsNewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.SiteType SiteTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpdateUserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ActiveRecordFlag {
            get {
                return this.ActiveRecordFlagField;
            }
            set {
                this.ActiveRecordFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Country {
            get {
                return this.CountryField;
            }
            set {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreateUserID {
            get {
                return this.CreateUserIDField;
            }
            set {
                this.CreateUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDirty {
            get {
                return this.IsDirtyField;
            }
            set {
                this.IsDirtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNew {
            get {
                return this.IsNewField;
            }
            set {
                this.IsNewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Location {
            get {
                return this.LocationField;
            }
            set {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHub {
            get {
                return this.ServerLangHubField;
            }
            set {
                this.ServerLangHubField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.SiteType SiteType {
            get {
                return this.SiteTypeField;
            }
            set {
                this.SiteTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdateUserID {
            get {
                return this.UpdateUserIDField;
            }
            set {
                this.UpdateUserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Menu", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Core")]
    [System.SerializableAttribute()]
    public partial class Menu : Pangea.BaseStructures.MultiLanguage, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessibilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.Menu[] AllSubMenusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreateUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAccessibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPermittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedMenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] MenuImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModuleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.Menu[] SubMenusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpdateUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ViewModelTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accessibility {
            get {
                return this.AccessibilityField;
            }
            set {
                this.AccessibilityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.Menu[] AllSubMenus {
            get {
                return this.AllSubMenusField;
            }
            set {
                this.AllSubMenusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreateUserID {
            get {
                return this.CreateUserIDField;
            }
            set {
                this.CreateUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAccessible {
            get {
                return this.IsAccessibleField;
            }
            set {
                this.IsAccessibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPermitted {
            get {
                return this.IsPermittedField;
            }
            set {
                this.IsPermittedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelectedMenu {
            get {
                return this.IsSelectedMenuField;
            }
            set {
                this.IsSelectedMenuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] MenuImage {
            get {
                return this.MenuImageField;
            }
            set {
                this.MenuImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Module {
            get {
                return this.ModuleField;
            }
            set {
                this.ModuleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                this.ParentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sequence {
            get {
                return this.SequenceField;
            }
            set {
                this.SequenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHub {
            get {
                return this.ServerLangHubField;
            }
            set {
                this.ServerLangHubField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.Menu[] SubMenus {
            get {
                return this.SubMenusField;
            }
            set {
                this.SubMenusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdateUserID {
            get {
                return this.UpdateUserIDField;
            }
            set {
                this.UpdateUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ViewModelTypeID {
            get {
                return this.ViewModelTypeIDField;
            }
            set {
                this.ViewModelTypeIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Core")]
    [System.SerializableAttribute()]
    public partial class Role : Pangea.BaseStructures.ObjectValidationBase, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreateUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.LogicalFunctionality[] LogicalFunctionalitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.Menu[] MenusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModuleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpdateUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.VisualFunctionality[] VisualFunctionalitiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreateUserID {
            get {
                return this.CreateUserIDField;
            }
            set {
                this.CreateUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.LogicalFunctionality[] LogicalFunctionalities {
            get {
                return this.LogicalFunctionalitiesField;
            }
            set {
                this.LogicalFunctionalitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.Menu[] Menus {
            get {
                return this.MenusField;
            }
            set {
                this.MenusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleID {
            get {
                return this.ModuleIDField;
            }
            set {
                this.ModuleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateDateTime {
            get {
                return this.UpdateDateTimeField;
            }
            set {
                this.UpdateDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdateUserID {
            get {
                return this.UpdateUserIDField;
            }
            set {
                this.UpdateUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.VisualFunctionality[] VisualFunctionalities {
            get {
                return this.VisualFunctionalitiesField;
            }
            set {
                this.VisualFunctionalitiesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalizedNames", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Core")]
    [System.SerializableAttribute()]
    public partial class LocalizedNames : Pangea.BaseStructures.ObjectValidationBase, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EN {
            get {
                return this.ENField;
            }
            set {
                this.ENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FR {
            get {
                return this.FRField;
            }
            set {
                this.FRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PT {
            get {
                return this.PTField;
            }
            set {
                this.PTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SP {
            get {
                return this.SPField;
            }
            set {
                this.SPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableName {
            get {
                return this.TableNameField;
            }
            set {
                this.TableNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogicalFunctionality", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Core")]
    [System.SerializableAttribute()]
    public partial class LogicalFunctionality : Pangea.BaseStructures.ObjectValidationBase, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHubField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHub {
            get {
                return this.ServerLangHubField;
            }
            set {
                this.ServerLangHubField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VisualFunctionality", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Core")]
    [System.SerializableAttribute()]
    public partial class VisualFunctionality : Pangea.BaseStructures.ObjectValidationBase, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveRecordFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDirtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEnableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsVisibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.Menu MenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHubField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActiveRecordFlag {
            get {
                return this.ActiveRecordFlagField;
            }
            set {
                this.ActiveRecordFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDirty {
            get {
                return this.IsDirtyField;
            }
            set {
                this.IsDirtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEnable {
            get {
                return this.IsEnableField;
            }
            set {
                this.IsEnableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVisible {
            get {
                return this.IsVisibleField;
            }
            set {
                this.IsVisibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.Menu Menu {
            get {
                return this.MenuField;
            }
            set {
                this.MenuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                this.RoleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHub {
            get {
                return this.ServerLangHubField;
            }
            set {
                this.ServerLangHubField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SiteType", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Core")]
    [System.SerializableAttribute()]
    public partial class SiteType : Pangea.BaseStructures.MultiLanguage, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveRecordFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHubField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActiveRecordFlag {
            get {
                return this.ActiveRecordFlagField;
            }
            set {
                this.ActiveRecordFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHub {
            get {
                return this.ServerLangHubField;
            }
            set {
                this.ServerLangHubField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sex", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Core")]
    [System.SerializableAttribute()]
    public partial class Sex : Pangea.BaseStructures.MultiLanguage, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveRecordFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHubField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActiveRecordFlag {
            get {
                return this.ActiveRecordFlagField;
            }
            set {
                this.ActiveRecordFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHub {
            get {
                return this.ServerLangHubField;
            }
            set {
                this.ServerLangHubField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Core")]
    [System.SerializableAttribute()]
    public partial class Country : Pangea.BaseStructures.MultiLanguage, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveRecordFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHubField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActiveRecordFlag {
            get {
                return this.ActiveRecordFlagField;
            }
            set {
                this.ActiveRecordFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGU.Interfaces.ApiAdmin.LocalizedNames ServerLangHub {
            get {
                return this.ServerLangHubField;
            }
            set {
                this.ServerLangHubField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemParameter", Namespace="http://schemas.datacontract.org/2004/07/NGU.Admin.Core")]
    [System.SerializableAttribute()]
    public partial class SystemParameter : Pangea.BaseStructures.ObjectValidationBase, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char ActiveRecordFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreateUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EditableFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InternalRemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModuleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpdateUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char ActiveRecordFlag {
            get {
                return this.ActiveRecordFlagField;
            }
            set {
                this.ActiveRecordFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreateUserID {
            get {
                return this.CreateUserIDField;
            }
            set {
                this.CreateUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EditableFlag {
            get {
                return this.EditableFlagField;
            }
            set {
                this.EditableFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalRemarks {
            get {
                return this.InternalRemarksField;
            }
            set {
                this.InternalRemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleID {
            get {
                return this.ModuleIDField;
            }
            set {
                this.ModuleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubjectID {
            get {
                return this.SubjectIDField;
            }
            set {
                this.SubjectIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateDate {
            get {
                return this.UpdateDateField;
            }
            set {
                this.UpdateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdateUserID {
            get {
                return this.UpdateUserIDField;
            }
            set {
                this.UpdateUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApiAdmin.IApiService")]
    public interface IApiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/IsAlive", ReplyAction="http://tempuri.org/IApiService/IsAliveResponse")]
        bool IsAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/CheckUserValidityWithPassword", ReplyAction="http://tempuri.org/IApiService/CheckUserValidityWithPasswordResponse")]
        NGU.Interfaces.ApiAdmin.UserValidation CheckUserValidityWithPassword(string username, string password, System.Nullable<Pangea.MultiLanguage.Languages> lang, System.Nullable<NGU.Interfaces.ApiAdmin.ModuleTypes> moduleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/UpdateUserPassword", ReplyAction="http://tempuri.org/IApiService/UpdateUserPasswordResponse")]
        NGU.Interfaces.ApiAdmin.UserValidation UpdateUserPassword(string username, string currentPassword, string newPassword, System.Nullable<Pangea.MultiLanguage.Languages> lang, System.Nullable<NGU.Interfaces.ApiAdmin.ModuleTypes> moduleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/GetUserListWithNamesOnly", ReplyAction="http://tempuri.org/IApiService/GetUserListWithNamesOnlyResponse")]
        NGU.Interfaces.ApiAdmin.User[] GetUserListWithNamesOnly();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/GetUserMenus", ReplyAction="http://tempuri.org/IApiService/GetUserMenusResponse")]
        NGU.Interfaces.ApiAdmin.Menu[] GetUserMenus(string username, Pangea.MultiLanguage.Languages lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/GetSystemParameters", ReplyAction="http://tempuri.org/IApiService/GetSystemParametersResponse")]
        NGU.Interfaces.ApiAdmin.SystemParameter[] GetSystemParameters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/GetGenders", ReplyAction="http://tempuri.org/IApiService/GetGendersResponse")]
        NGU.Interfaces.ApiAdmin.Sex[] GetGenders(Pangea.MultiLanguage.Languages lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/GetCountries", ReplyAction="http://tempuri.org/IApiService/GetCountriesResponse")]
        NGU.Interfaces.ApiAdmin.Country[] GetCountries(Pangea.MultiLanguage.Languages lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/GetIdenTypes", ReplyAction="http://tempuri.org/IApiService/GetIdenTypesResponse")]
        NGU.Interfaces.ApiAdmin.IdenType[] GetIdenTypes(Pangea.MultiLanguage.Languages lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/InsertLogoutUserLog", ReplyAction="http://tempuri.org/IApiService/InsertLogoutUserLogResponse")]
        void InsertLogoutUserLog(NGU.Interfaces.ApiAdmin.User user, NGU.Interfaces.ApiAdmin.ModuleTypes moduleID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApiServiceChannel : NGU.Interfaces.ApiAdmin.IApiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiServiceClient : System.ServiceModel.ClientBase<NGU.Interfaces.ApiAdmin.IApiService>, NGU.Interfaces.ApiAdmin.IApiService {
        
        public ApiServiceClient() {
        }
        
        public ApiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsAlive() {
            return base.Channel.IsAlive();
        }
        
        public NGU.Interfaces.ApiAdmin.UserValidation CheckUserValidityWithPassword(string username, string password, System.Nullable<Pangea.MultiLanguage.Languages> lang, System.Nullable<NGU.Interfaces.ApiAdmin.ModuleTypes> moduleID) {
            return base.Channel.CheckUserValidityWithPassword(username, password, lang, moduleID);
        }
        
        public NGU.Interfaces.ApiAdmin.UserValidation UpdateUserPassword(string username, string currentPassword, string newPassword, System.Nullable<Pangea.MultiLanguage.Languages> lang, System.Nullable<NGU.Interfaces.ApiAdmin.ModuleTypes> moduleID) {
            return base.Channel.UpdateUserPassword(username, currentPassword, newPassword, lang, moduleID);
        }
        
        public NGU.Interfaces.ApiAdmin.User[] GetUserListWithNamesOnly() {
            return base.Channel.GetUserListWithNamesOnly();
        }
        
        public NGU.Interfaces.ApiAdmin.Menu[] GetUserMenus(string username, Pangea.MultiLanguage.Languages lang) {
            return base.Channel.GetUserMenus(username, lang);
        }
        
        public NGU.Interfaces.ApiAdmin.SystemParameter[] GetSystemParameters() {
            return base.Channel.GetSystemParameters();
        }
        
        public NGU.Interfaces.ApiAdmin.Sex[] GetGenders(Pangea.MultiLanguage.Languages lang) {
            return base.Channel.GetGenders(lang);
        }
        
        public NGU.Interfaces.ApiAdmin.Country[] GetCountries(Pangea.MultiLanguage.Languages lang) {
            return base.Channel.GetCountries(lang);
        }
        
        public NGU.Interfaces.ApiAdmin.IdenType[] GetIdenTypes(Pangea.MultiLanguage.Languages lang) {
            return base.Channel.GetIdenTypes(lang);
        }
        
        public void InsertLogoutUserLog(NGU.Interfaces.ApiAdmin.User user, NGU.Interfaces.ApiAdmin.ModuleTypes moduleID) {
            base.Channel.InsertLogoutUserLog(user, moduleID);
        }
    }
}
