//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGU.Services.AbisService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AbisService.IAbisService")]
    public interface IAbisService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbisService/Enroll", ReplyAction="http://tempuri.org/IAbisService/EnrollResponse")]
        Pangea.Fingerprints.Interfaces.MatchingResult Enroll(byte[] subject, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbisService/Enroll", ReplyAction="http://tempuri.org/IAbisService/EnrollResponse")]
        System.Threading.Tasks.Task<Pangea.Fingerprints.Interfaces.MatchingResult> EnrollAsync(byte[] subject, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbisService/Delete", ReplyAction="http://tempuri.org/IAbisService/DeleteResponse")]
        Pangea.Fingerprints.Interfaces.PangeaBiometricStatus Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbisService/Delete", ReplyAction="http://tempuri.org/IAbisService/DeleteResponse")]
        System.Threading.Tasks.Task<Pangea.Fingerprints.Interfaces.PangeaBiometricStatus> DeleteAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAbisServiceChannel : NGU.Services.AbisService.IAbisService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AbisServiceClient : System.ServiceModel.ClientBase<NGU.Services.AbisService.IAbisService>, NGU.Services.AbisService.IAbisService {
        
        public AbisServiceClient() {
        }
        
        public AbisServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AbisServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AbisServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AbisServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pangea.Fingerprints.Interfaces.MatchingResult Enroll(byte[] subject, string id) {
            return base.Channel.Enroll(subject, id);
        }
        
        public System.Threading.Tasks.Task<Pangea.Fingerprints.Interfaces.MatchingResult> EnrollAsync(byte[] subject, string id) {
            return base.Channel.EnrollAsync(subject, id);
        }
        
        public Pangea.Fingerprints.Interfaces.PangeaBiometricStatus Delete(string id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<Pangea.Fingerprints.Interfaces.PangeaBiometricStatus> DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
