//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IISHostTest.PersonService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotifyPropertyChangedBase", Namespace="http://schemas.datacontract.org/2004/07/Pangea.BaseStructures")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.ObjectValidationBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.PersonDoc))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.Request))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.RequestReason))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.MultiLanguage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.RequestType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.RequestStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.Person))]
    public partial class NotifyPropertyChangedBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectValidationBase", Namespace="http://schemas.datacontract.org/2004/07/Pangea.BaseStructures")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.PersonDoc))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.Request))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.RequestReason))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.MultiLanguage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.RequestType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.RequestStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.Person))]
    public partial class ObjectValidationBase : IISHostTest.PersonService.NotifyPropertyChangedBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDoc", Namespace="http://schemas.datacontract.org/2004/07/NGU.Core")]
    [System.SerializableAttribute()]
    public partial class PersonDoc : IISHostTest.PersonService.ObjectValidationBase {
        
        private System.Nullable<System.DateTime> birthDateField;
        
        private System.Nullable<System.DateTime> createDateField;
        
        private int createUserIDField;
        
        private System.Nullable<System.DateTime> expirationDateField;
        
        private string firstNameField;
        
        private System.Nullable<int> genderIDField;
        
        private int iDField;
        
        private string identityCodeField;
        
        private int identityCountryIDField;
        
        private string identityNumField;
        
        private int identityTypeIDField;
        
        private System.Nullable<bool> isActiveRecordField;
        
        private System.Nullable<bool> isMainIdentifierField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        private int nationalityIDField;
        
        private IISHostTest.PersonService.Person personField;
        
        private IISHostTest.PersonService.Request requestField;
        
        private System.Nullable<System.DateTime> updateDateField;
        
        private int updateUserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> birthDate {
            get {
                return this.birthDateField;
            }
            set {
                if ((this.birthDateField.Equals(value) != true)) {
                    this.birthDateField = value;
                    this.RaisePropertyChanged("birthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> createDate {
            get {
                return this.createDateField;
            }
            set {
                if ((this.createDateField.Equals(value) != true)) {
                    this.createDateField = value;
                    this.RaisePropertyChanged("createDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int createUserID {
            get {
                return this.createUserIDField;
            }
            set {
                if ((this.createUserIDField.Equals(value) != true)) {
                    this.createUserIDField = value;
                    this.RaisePropertyChanged("createUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                if ((this.expirationDateField.Equals(value) != true)) {
                    this.expirationDateField = value;
                    this.RaisePropertyChanged("expirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> genderID {
            get {
                return this.genderIDField;
            }
            set {
                if ((this.genderIDField.Equals(value) != true)) {
                    this.genderIDField = value;
                    this.RaisePropertyChanged("genderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int iD {
            get {
                return this.iDField;
            }
            set {
                if ((this.iDField.Equals(value) != true)) {
                    this.iDField = value;
                    this.RaisePropertyChanged("iD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string identityCode {
            get {
                return this.identityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.identityCodeField, value) != true)) {
                    this.identityCodeField = value;
                    this.RaisePropertyChanged("identityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int identityCountryID {
            get {
                return this.identityCountryIDField;
            }
            set {
                if ((this.identityCountryIDField.Equals(value) != true)) {
                    this.identityCountryIDField = value;
                    this.RaisePropertyChanged("identityCountryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string identityNum {
            get {
                return this.identityNumField;
            }
            set {
                if ((object.ReferenceEquals(this.identityNumField, value) != true)) {
                    this.identityNumField = value;
                    this.RaisePropertyChanged("identityNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int identityTypeID {
            get {
                return this.identityTypeIDField;
            }
            set {
                if ((this.identityTypeIDField.Equals(value) != true)) {
                    this.identityTypeIDField = value;
                    this.RaisePropertyChanged("identityTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> isActiveRecord {
            get {
                return this.isActiveRecordField;
            }
            set {
                if ((this.isActiveRecordField.Equals(value) != true)) {
                    this.isActiveRecordField = value;
                    this.RaisePropertyChanged("isActiveRecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> isMainIdentifier {
            get {
                return this.isMainIdentifierField;
            }
            set {
                if ((this.isMainIdentifierField.Equals(value) != true)) {
                    this.isMainIdentifierField = value;
                    this.RaisePropertyChanged("isMainIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.middleNameField, value) != true)) {
                    this.middleNameField = value;
                    this.RaisePropertyChanged("middleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int nationalityID {
            get {
                return this.nationalityIDField;
            }
            set {
                if ((this.nationalityIDField.Equals(value) != true)) {
                    this.nationalityIDField = value;
                    this.RaisePropertyChanged("nationalityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IISHostTest.PersonService.Person person {
            get {
                return this.personField;
            }
            set {
                if ((object.ReferenceEquals(this.personField, value) != true)) {
                    this.personField = value;
                    this.RaisePropertyChanged("person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IISHostTest.PersonService.Request request {
            get {
                return this.requestField;
            }
            set {
                if ((object.ReferenceEquals(this.requestField, value) != true)) {
                    this.requestField = value;
                    this.RaisePropertyChanged("request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> updateDate {
            get {
                return this.updateDateField;
            }
            set {
                if ((this.updateDateField.Equals(value) != true)) {
                    this.updateDateField = value;
                    this.RaisePropertyChanged("updateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int updateUserID {
            get {
                return this.updateUserIDField;
            }
            set {
                if ((this.updateUserIDField.Equals(value) != true)) {
                    this.updateUserIDField = value;
                    this.RaisePropertyChanged("updateUserID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/NGU.Core")]
    [System.SerializableAttribute()]
    public partial class Request : IISHostTest.PersonService.ObjectValidationBase {
        
        private System.Nullable<System.DateTime> birthDateField;
        
        private System.Nullable<System.DateTime> createDateField;
        
        private int createUserIDField;
        
        private string docCodeField;
        
        private System.Nullable<System.DateTime> docExpirationDateField;
        
        private string docNationalityIDField;
        
        private string firstNameField;
        
        private System.Nullable<int> genderIDField;
        
        private int iDField;
        
        private System.Nullable<int> idenCountryIDField;
        
        private string idenNumField;
        
        private int idenTypeIDField;
        
        private System.Nullable<bool> isMatch1ToManyResField;
        
        private System.Nullable<bool> isMatch1ToOneResField;
        
        private System.Nullable<bool> isMatchTextDataResField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        private string numField;
        
        private IISHostTest.PersonService.Person personField;
        
        private int priorityIDField;
        
        private string remarksField;
        
        private IISHostTest.PersonService.RequestReason requestReasonField;
        
        private IISHostTest.PersonService.RequestStatus requestStatusField;
        
        private IISHostTest.PersonService.RequestType requestSubTypeField;
        
        private IISHostTest.PersonService.RequestType requestTypeField;
        
        private int siteIDField;
        
        private System.Nullable<System.DateTime> statusDateField;
        
        private System.Nullable<System.DateTime> updateDateField;
        
        private int updateUserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> birthDate {
            get {
                return this.birthDateField;
            }
            set {
                if ((this.birthDateField.Equals(value) != true)) {
                    this.birthDateField = value;
                    this.RaisePropertyChanged("birthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> createDate {
            get {
                return this.createDateField;
            }
            set {
                if ((this.createDateField.Equals(value) != true)) {
                    this.createDateField = value;
                    this.RaisePropertyChanged("createDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int createUserID {
            get {
                return this.createUserIDField;
            }
            set {
                if ((this.createUserIDField.Equals(value) != true)) {
                    this.createUserIDField = value;
                    this.RaisePropertyChanged("createUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string docCode {
            get {
                return this.docCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.docCodeField, value) != true)) {
                    this.docCodeField = value;
                    this.RaisePropertyChanged("docCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> docExpirationDate {
            get {
                return this.docExpirationDateField;
            }
            set {
                if ((this.docExpirationDateField.Equals(value) != true)) {
                    this.docExpirationDateField = value;
                    this.RaisePropertyChanged("docExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string docNationalityID {
            get {
                return this.docNationalityIDField;
            }
            set {
                if ((object.ReferenceEquals(this.docNationalityIDField, value) != true)) {
                    this.docNationalityIDField = value;
                    this.RaisePropertyChanged("docNationalityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> genderID {
            get {
                return this.genderIDField;
            }
            set {
                if ((this.genderIDField.Equals(value) != true)) {
                    this.genderIDField = value;
                    this.RaisePropertyChanged("genderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int iD {
            get {
                return this.iDField;
            }
            set {
                if ((this.iDField.Equals(value) != true)) {
                    this.iDField = value;
                    this.RaisePropertyChanged("iD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> idenCountryID {
            get {
                return this.idenCountryIDField;
            }
            set {
                if ((this.idenCountryIDField.Equals(value) != true)) {
                    this.idenCountryIDField = value;
                    this.RaisePropertyChanged("idenCountryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string idenNum {
            get {
                return this.idenNumField;
            }
            set {
                if ((object.ReferenceEquals(this.idenNumField, value) != true)) {
                    this.idenNumField = value;
                    this.RaisePropertyChanged("idenNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idenTypeID {
            get {
                return this.idenTypeIDField;
            }
            set {
                if ((this.idenTypeIDField.Equals(value) != true)) {
                    this.idenTypeIDField = value;
                    this.RaisePropertyChanged("idenTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> isMatch1ToManyRes {
            get {
                return this.isMatch1ToManyResField;
            }
            set {
                if ((this.isMatch1ToManyResField.Equals(value) != true)) {
                    this.isMatch1ToManyResField = value;
                    this.RaisePropertyChanged("isMatch1ToManyRes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> isMatch1ToOneRes {
            get {
                return this.isMatch1ToOneResField;
            }
            set {
                if ((this.isMatch1ToOneResField.Equals(value) != true)) {
                    this.isMatch1ToOneResField = value;
                    this.RaisePropertyChanged("isMatch1ToOneRes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> isMatchTextDataRes {
            get {
                return this.isMatchTextDataResField;
            }
            set {
                if ((this.isMatchTextDataResField.Equals(value) != true)) {
                    this.isMatchTextDataResField = value;
                    this.RaisePropertyChanged("isMatchTextDataRes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.middleNameField, value) != true)) {
                    this.middleNameField = value;
                    this.RaisePropertyChanged("middleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string num {
            get {
                return this.numField;
            }
            set {
                if ((object.ReferenceEquals(this.numField, value) != true)) {
                    this.numField = value;
                    this.RaisePropertyChanged("num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IISHostTest.PersonService.Person person {
            get {
                return this.personField;
            }
            set {
                if ((object.ReferenceEquals(this.personField, value) != true)) {
                    this.personField = value;
                    this.RaisePropertyChanged("person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int priorityID {
            get {
                return this.priorityIDField;
            }
            set {
                if ((this.priorityIDField.Equals(value) != true)) {
                    this.priorityIDField = value;
                    this.RaisePropertyChanged("priorityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                if ((object.ReferenceEquals(this.remarksField, value) != true)) {
                    this.remarksField = value;
                    this.RaisePropertyChanged("remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IISHostTest.PersonService.RequestReason requestReason {
            get {
                return this.requestReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.requestReasonField, value) != true)) {
                    this.requestReasonField = value;
                    this.RaisePropertyChanged("requestReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IISHostTest.PersonService.RequestStatus requestStatus {
            get {
                return this.requestStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.requestStatusField, value) != true)) {
                    this.requestStatusField = value;
                    this.RaisePropertyChanged("requestStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IISHostTest.PersonService.RequestType requestSubType {
            get {
                return this.requestSubTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.requestSubTypeField, value) != true)) {
                    this.requestSubTypeField = value;
                    this.RaisePropertyChanged("requestSubType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IISHostTest.PersonService.RequestType requestType {
            get {
                return this.requestTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.requestTypeField, value) != true)) {
                    this.requestTypeField = value;
                    this.RaisePropertyChanged("requestType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int siteID {
            get {
                return this.siteIDField;
            }
            set {
                if ((this.siteIDField.Equals(value) != true)) {
                    this.siteIDField = value;
                    this.RaisePropertyChanged("siteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> statusDate {
            get {
                return this.statusDateField;
            }
            set {
                if ((this.statusDateField.Equals(value) != true)) {
                    this.statusDateField = value;
                    this.RaisePropertyChanged("statusDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> updateDate {
            get {
                return this.updateDateField;
            }
            set {
                if ((this.updateDateField.Equals(value) != true)) {
                    this.updateDateField = value;
                    this.RaisePropertyChanged("updateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int updateUserID {
            get {
                return this.updateUserIDField;
            }
            set {
                if ((this.updateUserIDField.Equals(value) != true)) {
                    this.updateUserIDField = value;
                    this.RaisePropertyChanged("updateUserID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestReason", Namespace="http://schemas.datacontract.org/2004/07/NGU.Core")]
    [System.SerializableAttribute()]
    public partial class RequestReason : IISHostTest.PersonService.ObjectValidationBase {
        
        private string codeField;
        
        private string descriptionField;
        
        private int iDField;
        
        private System.Nullable<bool> isActiveRecordField;
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int iD {
            get {
                return this.iDField;
            }
            set {
                if ((this.iDField.Equals(value) != true)) {
                    this.iDField = value;
                    this.RaisePropertyChanged("iD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> isActiveRecord {
            get {
                return this.isActiveRecordField;
            }
            set {
                if ((this.isActiveRecordField.Equals(value) != true)) {
                    this.isActiveRecordField = value;
                    this.RaisePropertyChanged("isActiveRecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultiLanguage", Namespace="http://schemas.datacontract.org/2004/07/Pangea.BaseStructures")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.RequestType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IISHostTest.PersonService.RequestStatus))]
    public partial class MultiLanguage : IISHostTest.PersonService.ObjectValidationBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionMLCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionTranslatedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionMLCode {
            get {
                return this.DescriptionMLCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionMLCodeField, value) != true)) {
                    this.DescriptionMLCodeField = value;
                    this.RaisePropertyChanged("DescriptionMLCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionTranslated {
            get {
                return this.DescriptionTranslatedField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionTranslatedField, value) != true)) {
                    this.DescriptionTranslatedField = value;
                    this.RaisePropertyChanged("DescriptionTranslated");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestType", Namespace="http://schemas.datacontract.org/2004/07/NGU.Core")]
    [System.SerializableAttribute()]
    public partial class RequestType : IISHostTest.PersonService.MultiLanguage {
        
        private System.Nullable<bool> activeRecordFlagField;
        
        private string codeField;
        
        private int iDField;
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> activeRecordFlag {
            get {
                return this.activeRecordFlagField;
            }
            set {
                if ((this.activeRecordFlagField.Equals(value) != true)) {
                    this.activeRecordFlagField = value;
                    this.RaisePropertyChanged("activeRecordFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int iD {
            get {
                return this.iDField;
            }
            set {
                if ((this.iDField.Equals(value) != true)) {
                    this.iDField = value;
                    this.RaisePropertyChanged("iD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestStatus", Namespace="http://schemas.datacontract.org/2004/07/NGU.Core")]
    [System.SerializableAttribute()]
    public partial class RequestStatus : IISHostTest.PersonService.MultiLanguage {
        
        private System.Nullable<bool> activeRecordFlagField;
        
        private string codeField;
        
        private int iDField;
        
        private System.Nullable<bool> inProcessFlagField;
        
        private string internalRemarksField;
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> activeRecordFlag {
            get {
                return this.activeRecordFlagField;
            }
            set {
                if ((this.activeRecordFlagField.Equals(value) != true)) {
                    this.activeRecordFlagField = value;
                    this.RaisePropertyChanged("activeRecordFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int iD {
            get {
                return this.iDField;
            }
            set {
                if ((this.iDField.Equals(value) != true)) {
                    this.iDField = value;
                    this.RaisePropertyChanged("iD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> inProcessFlag {
            get {
                return this.inProcessFlagField;
            }
            set {
                if ((this.inProcessFlagField.Equals(value) != true)) {
                    this.inProcessFlagField = value;
                    this.RaisePropertyChanged("inProcessFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string internalRemarks {
            get {
                return this.internalRemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.internalRemarksField, value) != true)) {
                    this.internalRemarksField = value;
                    this.RaisePropertyChanged("internalRemarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/NGU.Core")]
    [System.SerializableAttribute()]
    public partial class Person : IISHostTest.PersonService.ObjectValidationBase {
        
        private System.Nullable<System.DateTime> birthDateField;
        
        private System.Nullable<System.DateTime> createDateField;
        
        private int createUserIDField;
        
        private string firstNameField;
        
        private System.Nullable<int> genderIDField;
        
        private int iDField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        private System.Nullable<int> nationalityIDField;
        
        private int statusIDField;
        
        private System.Nullable<System.DateTime> updateDateField;
        
        private int updateUserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> birthDate {
            get {
                return this.birthDateField;
            }
            set {
                if ((this.birthDateField.Equals(value) != true)) {
                    this.birthDateField = value;
                    this.RaisePropertyChanged("birthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> createDate {
            get {
                return this.createDateField;
            }
            set {
                if ((this.createDateField.Equals(value) != true)) {
                    this.createDateField = value;
                    this.RaisePropertyChanged("createDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int createUserID {
            get {
                return this.createUserIDField;
            }
            set {
                if ((this.createUserIDField.Equals(value) != true)) {
                    this.createUserIDField = value;
                    this.RaisePropertyChanged("createUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> genderID {
            get {
                return this.genderIDField;
            }
            set {
                if ((this.genderIDField.Equals(value) != true)) {
                    this.genderIDField = value;
                    this.RaisePropertyChanged("genderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int iD {
            get {
                return this.iDField;
            }
            set {
                if ((this.iDField.Equals(value) != true)) {
                    this.iDField = value;
                    this.RaisePropertyChanged("iD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.middleNameField, value) != true)) {
                    this.middleNameField = value;
                    this.RaisePropertyChanged("middleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> nationalityID {
            get {
                return this.nationalityIDField;
            }
            set {
                if ((this.nationalityIDField.Equals(value) != true)) {
                    this.nationalityIDField = value;
                    this.RaisePropertyChanged("nationalityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int statusID {
            get {
                return this.statusIDField;
            }
            set {
                if ((this.statusIDField.Equals(value) != true)) {
                    this.statusIDField = value;
                    this.RaisePropertyChanged("statusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> updateDate {
            get {
                return this.updateDateField;
            }
            set {
                if ((this.updateDateField.Equals(value) != true)) {
                    this.updateDateField = value;
                    this.RaisePropertyChanged("updateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int updateUserID {
            get {
                return this.updateUserIDField;
            }
            set {
                if ((this.updateUserIDField.Equals(value) != true)) {
                    this.updateUserIDField = value;
                    this.RaisePropertyChanged("updateUserID");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonService.IPersonService")]
    public interface IPersonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/IsAlive", ReplyAction="http://tempuri.org/IBaseService/IsAliveResponse")]
        bool IsAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/IsAlive", ReplyAction="http://tempuri.org/IBaseService/IsAliveResponse")]
        System.Threading.Tasks.Task<bool> IsAliveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPerson", ReplyAction="http://tempuri.org/IPersonService/GetPersonResponse")]
        IISHostTest.PersonService.Person GetPerson(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPerson", ReplyAction="http://tempuri.org/IPersonService/GetPersonResponse")]
        System.Threading.Tasks.Task<IISHostTest.PersonService.Person> GetPersonAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPersonDoc", ReplyAction="http://tempuri.org/IPersonService/GetPersonDocResponse")]
        IISHostTest.PersonService.PersonDoc GetPersonDoc(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPersonDoc", ReplyAction="http://tempuri.org/IPersonService/GetPersonDocResponse")]
        System.Threading.Tasks.Task<IISHostTest.PersonService.PersonDoc> GetPersonDocAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/SearchPersonByDoc", ReplyAction="http://tempuri.org/IPersonService/SearchPersonByDocResponse")]
        IISHostTest.PersonService.Person SearchPersonByDoc(int docType, string docNumber, int country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/SearchPersonByDoc", ReplyAction="http://tempuri.org/IPersonService/SearchPersonByDocResponse")]
        System.Threading.Tasks.Task<IISHostTest.PersonService.Person> SearchPersonByDocAsync(int docType, string docNumber, int country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/SaveFingerprints", ReplyAction="http://tempuri.org/IPersonService/SaveFingerprintsResponse")]
        void SaveFingerprints(int requestId, int userId, System.Collections.Generic.Dictionary<Pangea.Fingerprints.Interfaces.FPIndexes, byte[]> fingerData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/SaveFingerprints", ReplyAction="http://tempuri.org/IPersonService/SaveFingerprintsResponse")]
        System.Threading.Tasks.Task SaveFingerprintsAsync(int requestId, int userId, System.Collections.Generic.Dictionary<Pangea.Fingerprints.Interfaces.FPIndexes, byte[]> fingerData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonServiceChannel : IISHostTest.PersonService.IPersonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonServiceClient : System.ServiceModel.ClientBase<IISHostTest.PersonService.IPersonService>, IISHostTest.PersonService.IPersonService {
        
        public PersonServiceClient() {
        }
        
        public PersonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsAlive() {
            return base.Channel.IsAlive();
        }
        
        public System.Threading.Tasks.Task<bool> IsAliveAsync() {
            return base.Channel.IsAliveAsync();
        }
        
        public IISHostTest.PersonService.Person GetPerson(int ID) {
            return base.Channel.GetPerson(ID);
        }
        
        public System.Threading.Tasks.Task<IISHostTest.PersonService.Person> GetPersonAsync(int ID) {
            return base.Channel.GetPersonAsync(ID);
        }
        
        public IISHostTest.PersonService.PersonDoc GetPersonDoc(int ID) {
            return base.Channel.GetPersonDoc(ID);
        }
        
        public System.Threading.Tasks.Task<IISHostTest.PersonService.PersonDoc> GetPersonDocAsync(int ID) {
            return base.Channel.GetPersonDocAsync(ID);
        }
        
        public IISHostTest.PersonService.Person SearchPersonByDoc(int docType, string docNumber, int country) {
            return base.Channel.SearchPersonByDoc(docType, docNumber, country);
        }
        
        public System.Threading.Tasks.Task<IISHostTest.PersonService.Person> SearchPersonByDocAsync(int docType, string docNumber, int country) {
            return base.Channel.SearchPersonByDocAsync(docType, docNumber, country);
        }
        
        public void SaveFingerprints(int requestId, int userId, System.Collections.Generic.Dictionary<Pangea.Fingerprints.Interfaces.FPIndexes, byte[]> fingerData) {
            base.Channel.SaveFingerprints(requestId, userId, fingerData);
        }
        
        public System.Threading.Tasks.Task SaveFingerprintsAsync(int requestId, int userId, System.Collections.Generic.Dictionary<Pangea.Fingerprints.Interfaces.FPIndexes, byte[]> fingerData) {
            return base.Channel.SaveFingerprintsAsync(requestId, userId, fingerData);
        }
    }
}
